global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. -  fetch the metrics from the individual microservice containers every five seconds and using the  same metrics,
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'product:8080' ]   # based on the  service name (ie: accounts, loans) mentioned in Docker compose
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order:8081' ]
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user:8082' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8075' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8761' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8073' ]
  
