server:
  port: 8080

spring:
  config:
    activate:
    on-profile: default
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  health:
    circuitbreakers:
      enabled: true

#server:
#  port: 8130
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/product
##    url: jdbc:mysql://localhost:3307/embarkx
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0
#
#app:
#  message: "Hello Product!"
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#
#logging:
#  file:
#    name: logs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7