#https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_spring_cloud_config_server

spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
    #active: git
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8072
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:
#      enabled: true
#  endpoint:
#    health:
#      probes:
#        enabled: true